CREATE TABLE USER_INFO (
    USER_ID   NUMBER      PRIMARY KEY,
    GENDER    NUMBER(1),          -- 1: 남성, 0: 여성, NULL: 미기재
    AGE       NUMBER,
    JOINED    DATE        NOT NULL
);

INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (1, 1, 26, TO_DATE('2021-06-01', 'YYYY-MM-DD'));
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (2, NULL, NULL, TO_DATE('2021-06-25', 'YYYY-MM-DD'));
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (3, 0, NULL, TO_DATE('2021-06-30', 'YYYY-MM-DD'));
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (4, 0, 31, TO_DATE('2021-07-03', 'YYYY-MM-DD'));
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (5, 1, 25, TO_DATE('2022-01-09', 'YYYY-MM-DD'));
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (6, 1, 33, TO_DATE('2022-02-14', 'YYYY-MM-DD'));